server {
    listen 80;
    server_name _;
    root /var/www/html;
    index index.html;

    client_max_body_size 20m;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /index.html {
        try_files $uri =404;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /api/ {
        proxy_pass http://192.168.1.61:9192/api/;
        proxy_set_header GROCY-API-KEY "${GROCY_API_KEY}";
        proxy_set_header Host "192.168.1.61:9192";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_request_buffering off;
        proxy_connect_timeout 10s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}
